# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: "main"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    target-branch: "main"
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /
    target-branch: "dev/1.x.x"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev/1.x.x"
    schedule:
      interval: weekly