#include <openssl/evp.h>

void test_evp_cipher() {
    EVP_PKEY_CTX* ctx = NULL;
    EVP_CIPHER_CTX* cctx = NULL;
    unsigned char buf[64];
    size_t len = 0;

    EVP_aes_128_cbc();
    EVP_aes_128_ecb();
    EVP_aes_128_gcm();
    EVP_aes_128_ctr();
    EVP_aes_128_ccm();
    EVP_aes_128_cfb128();
    EVP_aes_128_cfb1();
    EVP_aes_128_cfb8();
    EVP_aes_128_ofb();
    EVP_aes_128_xts();
    EVP_aes_128_ocb();
    EVP_aes_128_wrap();
    EVP_aes_128_wrap_pad();
    EVP_aes_192_cbc();
    EVP_aes_192_ecb();
    EVP_aes_192_gcm();
    EVP_aes_192_ctr();
    EVP_aes_192_ccm();
    EVP_aes_192_cfb128();
    EVP_aes_192_cfb1();
    EVP_aes_192_cfb8();
    EVP_aes_192_ofb();
    EVP_aes_192_ocb();
    EVP_aes_192_wrap();
    EVP_aes_192_wrap_pad();
    EVP_aes_256_cbc();
    EVP_aes_256_ecb();
    EVP_aes_256_gcm();
    EVP_aes_256_ctr();
    EVP_aes_256_ccm();
    EVP_aes_256_cfb128();
    EVP_aes_256_cfb1();
    EVP_aes_256_cfb8();
    EVP_aes_256_ofb();
    EVP_aes_256_xts();
    EVP_aes_256_ocb();
    EVP_aes_256_wrap();
    EVP_aes_256_wrap_pad();
    EVP_camellia_128_ecb();
    EVP_camellia_128_cbc();
    EVP_camellia_128_cfb128();
    EVP_camellia_128_cfb1();
    EVP_camellia_128_cfb8();
    EVP_camellia_128_ofb();
    EVP_camellia_128_ctr();
    EVP_camellia_192_ecb();
    EVP_camellia_192_cbc();
    EVP_camellia_192_cfb128();
    EVP_camellia_192_cfb1();
    EVP_camellia_192_cfb8();
    EVP_camellia_192_ofb();
    EVP_camellia_192_ctr();
    EVP_camellia_256_ecb();
    EVP_camellia_256_cbc();
    EVP_camellia_256_cfb128();
    EVP_camellia_256_cfb1();
    EVP_camellia_256_cfb8();
    EVP_camellia_256_ofb();
    EVP_camellia_256_ctr();
    EVP_aria_128_ecb();
    EVP_aria_128_cbc();
    EVP_aria_128_cfb128();
    EVP_aria_128_cfb1();
    EVP_aria_128_cfb8();
    EVP_aria_128_ofb();
    EVP_aria_128_ctr();
    EVP_aria_128_gcm();
    EVP_aria_128_ccm();
    EVP_aria_192_ecb();
    EVP_aria_192_cbc();
    EVP_aria_192_cfb128();
    EVP_aria_192_cfb1();
    EVP_aria_192_cfb8();
    EVP_aria_192_ofb();
    EVP_aria_192_ctr();
    EVP_aria_192_gcm();
    EVP_aria_192_ccm();
    EVP_aria_256_ecb();
    EVP_aria_256_cbc();
    EVP_aria_256_cfb128();
    EVP_aria_256_cfb1();
    EVP_aria_256_cfb8();
    EVP_aria_256_ofb();
    EVP_aria_256_ctr();
    EVP_aria_256_gcm();
    EVP_aria_256_ccm();
    EVP_sm4_ecb();
    EVP_sm4_cbc();
    EVP_sm4_cfb128();
    EVP_sm4_ofb();
    EVP_sm4_ctr();
    EVP_des_cbc();
    EVP_des_ecb();
    EVP_des_ede3_cbc();
    EVP_des_cfb64();
    EVP_des_cfb1();
    EVP_des_cfb8();
    EVP_des_ofb();
    EVP_des_ede();
    EVP_des_ede_ecb();
    EVP_des_ede_cbc();
    EVP_des_ede_cfb64();
    EVP_des_ede_ofb();
    EVP_des_ede3();
    EVP_des_ede3_ecb();
    EVP_des_ede3_cfb1();
    EVP_des_ede3_cfb8();
    EVP_des_ede3_cfb64();
    EVP_des_ede3_ofb();
    EVP_desx_cbc();
    EVP_bf_ecb();
    EVP_bf_cbc();
    EVP_bf_cfb64();
    EVP_bf_ofb();
    EVP_cast5_ecb();
    EVP_cast5_cbc();
    EVP_cast5_cfb64();
    EVP_cast5_ofb();
    EVP_rc2_ecb();
    EVP_rc2_cbc();
    EVP_rc2_cfb64();
    EVP_rc2_ofb();
    EVP_rc2_40_cbc();
    EVP_rc2_64_cbc();
    EVP_rc4();
    EVP_rc4_40();
    EVP_rc4_hmac_md5();
    EVP_rc5_32_12_16_ecb();
    EVP_rc5_32_12_16_cbc();
    EVP_rc5_32_12_16_cfb64();
    EVP_rc5_32_12_16_ofb();
    EVP_idea_ecb();
    EVP_idea_cbc();
    EVP_idea_cfb64();
    EVP_idea_ofb();
    EVP_seed_ecb();
    EVP_seed_cbc();
    EVP_seed_cfb128();
    EVP_seed_ofb();
    EVP_chacha20();
    EVP_chacha20_poly1305();
    EVP_aes_128_cbc_hmac_sha1();
    EVP_aes_256_cbc_hmac_sha1();
    EVP_aes_128_cbc_hmac_sha256();
    EVP_aes_256_cbc_hmac_sha256();
    EVP_PKEY_encrypt(ctx, buf, &len, buf, 64);
    EVP_PKEY_encrypt_init(ctx);
    EVP_PKEY_encrypt_init_ex(ctx, NULL);
    EVP_PKEY_decrypt(ctx, buf, &len, buf, 64);
    EVP_PKEY_decrypt_init(ctx);
    EVP_PKEY_decrypt_init_ex(ctx, NULL);
    EVP_PKEY_CTX_set_rsa_padding(ctx, 4);
    const EVP_MD* oaep_md = EVP_sha256();
    EVP_PKEY_CTX_set_rsa_oaep_md(ctx, oaep_md);
    // md_name given as the OpenSSL 3.x provider fetch name.
    EVP_PKEY_CTX_set_rsa_oaep_md_name(ctx, "SHA2-256", NULL);
    EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, buf, 16);
    EVP_EncryptInit(cctx, NULL, buf, buf);
    EVP_EncryptInit_ex(cctx, NULL, NULL, buf, buf);
    EVP_EncryptInit_ex2(cctx, NULL, buf, buf, NULL);
    EVP_DecryptInit(cctx, NULL, buf, buf);
    EVP_DecryptInit_ex(cctx, NULL, NULL, buf, buf);
    EVP_DecryptInit_ex2(cctx, NULL, buf, buf, NULL);
    EVP_CipherInit(cctx, NULL, buf, buf, 1);
    EVP_CipherInit_ex(cctx, NULL, NULL, buf, buf, 1);
    EVP_CipherInit_ex2(cctx, NULL, buf, buf, 1, NULL);
    EVP_ASYM_CIPHER_fetch(NULL, "RSA", NULL);
    EVP_get_cipherbyname("AES-256-GCM");
    EVP_des_ede3_wrap();
    EVP_enc_null();
    CMS_encrypt(NULL, buf, NULL, NULL);
    CMS_encrypt_ex(NULL, buf, NULL, NULL, NULL, 0);
    CMS_EnvelopedData_create(NULL);
    CMS_EnvelopedData_create_ex(NULL, NULL, NULL);
    CMS_AuthEnvelopedData_create(NULL);
    CMS_AuthEnvelopedData_create_ex(NULL, NULL, NULL);
    CMS_EncryptedData_encrypt(NULL, buf, NULL, 16, 0);
    CMS_EncryptedData_encrypt_ex(NULL, buf, NULL, 16, 0, NULL, NULL);
    CMS_EncryptedData_set1_key(NULL, NULL, buf, 32);
    CMS_add0_recipient_key(NULL, 0, buf, 16, buf, 8, NULL, NULL, NULL);
    PKCS7_encrypt(NULL, buf, NULL, 0);
    PKCS7_encrypt_ex(NULL, buf, NULL, 0, NULL, NULL);
    PKCS7_set_cipher(NULL, NULL);
}
