# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build-java-17:
    runs-on: ubuntu-latest
    env:
      SONAR_JRE: '17'
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Deploy to GitHub Packages
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

  build-java-11:
    runs-on: ubuntu-latest
    env:
      SONAR_JRE: '11'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Deploy to GitHub Packages
        run: |
          export MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          mvn versions:set -DnewVersion=$MVN_VERSION-jre11
          mvn versions:commit
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
